import { useState, useRef, useEffect } from "react";
import { useAuth } from "@/hooks/use-auth";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Headphones, X, Home, MessageSquare, HelpCircle, Send, ChevronRight, Mail, Sparkles, AlertCircle } from "lucide-react";
import { cn } from "@/lib/utils";
import { toast } from "sonner";

type Message = {
  id: string;
  sender: "bot" | "user";
  text: string;
  timestamp: Date;
};

export function SupportWidget() {
  const { user } = useAuth();
  const [isOpen, setIsOpen] = useState(false);
  const [activeTab, setActiveTab] = useState<"home" | "messages" | "help">("home");
  const [searchQuery, setSearchQuery] = useState("");
  const [inputText, setInputText] = useState("");
  const [isTyping, setIsTyping] = useState(false);
  const [messages, setMessages] = useState<Message[]>([
    {
      id: "welcome",
      sender: "bot",
      text: "Hey! Welcome to resume-zen Ai Support. How can I help you today? Pick an option below or type a query.",
      timestamp: new Date(),
    },
  ]);

  const chatEndRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    chatEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages, isTyping]);

  const faqs = [
    {
      q: "How do I unlock my resume with Premium?",
      a: "Click 'Download Clean PDF' or 'Upgrade' in the builder sub-header. Complete the ₹49 UPI payment via the secure Razorpay page, copy the 12-digit UTR Transaction ID, paste it into the verification input, and click verify. Your resume will finalize and unlock instantly!",
    },
    {
      q: "What is the UPI UTR Reference Number?",
      a: "The UTR (Unique Transaction Reference) is a 12-digit numeric code generated by your payment provider (GPay, PhonePe, Paytm, BHIM) upon successful transfer. It is listed as 'UPI Ref No.', 'UTR', or 'Transaction ID' in your app's transaction receipt.",
    },
    {
      q: "My payment failed / money debited but didn't unlock?",
      a: "Don't worry! Simply copy your 12-digit UPI UTR number and email it directly to jayeshneo07@gmail.com. Jayesh will manually verify your settlement code and unlock your resume instantly within 5 minutes.",
    },
    {
      q: "Why is my resume frozen & locked after payment?",
      a: "Premium resumes are finalized and locked from further edits to preserve version control, target language formatting, and PDF layout. If you need to make changes, go to your Dashboard and click 'Duplicate' to create an editable free copy instantly!",
    },
  ];

  const filteredFaqs = faqs.filter(
    (faq) =>
      faq.q.toLowerCase().includes(searchQuery.toLowerCase()) ||
      faq.a.toLowerCase().includes(searchQuery.toLowerCase())
  );

  const simulateBotReply = (userText: string) => {
    setIsTyping(true);
    setTimeout(() => {
      let replyText = "";
      const text = userText.toLowerCase();

      if (text.includes("pay") || text.includes("fail") || text.includes("money") || text.includes("refund") || text.includes("charge")) {
        replyText = "For payment failures, please transfer ₹49 via the UPI link, copy your 12-digit UTR code, and input it in the checkout modal. If money was debited but the resume didn't unlock, email your UTR to jayeshneo07@gmail.com for instant activation.";
      } else if (text.includes("lock") || text.includes("edit") || text.includes("change") || text.includes("freeze")) {
        replyText = "Unlocked resumes are finalized and frozen. To edit again, simply navigate to your Dashboard and click 'Duplicate' on your resume to spawn an editable free copy.";
      } else if (text.includes("utr") || text.includes("ref") || text.includes("transaction")) {
        replyText = "The UTR is a 12-digit number found on your GPay, PhonePe, or Paytm receipt. Enter this numeric code in the checkout box to trigger our automated ledger verification.";
      } else if (text.includes("contact") || text.includes("email") || text.includes("help") || text.includes("support")) {
        replyText = "You can contact Jayesh directly at jayeshneo07@gmail.com. We are online 24/7 to help resolve payment or resume issues!";
      } else {
        replyText = "Thank you for reaching out! For payment queries, double check your 12-digit UPI UTR. You can also write directly to Jayesh at jayeshneo07@gmail.com for dedicated support.";
      }

      setMessages((prev) => [
        ...prev,
        {
          id: Math.random().toString(),
          sender: "bot",
          text: replyText,
          timestamp: new Date(),
        },
      ]);
      setIsTyping(false);
    }, 1200);
  };

  const handleSendMessage = (textToSend?: string) => {
    const text = textToSend || inputText.trim();
    if (!text) return;

    if (!textToSend) setInputText("");

    const newMsg: Message = {
      id: Math.random().toString(),
      sender: "user",
      text,
      timestamp: new Date(),
    };

    setMessages((prev) => [...prev, newMsg]);
    simulateBotReply(text);
  };

  const handleOptionClick = (option: string, query: string) => {
    const newMsg: Message = {
      id: Math.random().toString(),
      sender: "user",
      text: option,
      timestamp: new Date(),
    };
    setMessages((prev) => [...prev, newMsg]);
    simulateBotReply(query);
  };

  return (
    <div className="fixed bottom-6 right-6 z-50 print:hidden select-none">
      {/* Floating Toggle Button */}
      <button
        onClick={() => setIsOpen(!isOpen)}
        className={cn(
          "h-14 w-14 rounded-full bg-neutral-950 hover:bg-neutral-900 border border-neutral-800 text-white flex items-center justify-center shadow-2xl transition-all duration-300 transform hover:scale-105 active:scale-95 cursor-pointer relative",
          isOpen ? "rotate-90 bg-destructive hover:bg-destructive/90 border-destructive/30" : ""
        )}
      >
        {isOpen ? <X className="h-6 w-6" /> : <Headphones className="h-6 w-6" />}
        {!isOpen && (
          <span className="absolute -top-1 -right-1 flex h-4 w-4">
            <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-amber-400 opacity-75"></span>
            <span className="relative inline-flex rounded-full h-4 w-4 bg-amber-500 text-[9px] font-bold text-neutral-950 items-center justify-center">1</span>
          </span>
        )}
      </button>

      {/* Support Card Container */}
      {isOpen && (
        <div className="absolute bottom-16 right-0 w-[360px] sm:w-[380px] h-[550px] bg-card text-card-foreground border border-border rounded-3xl shadow-2xl overflow-hidden flex flex-col animate-in slide-in-from-bottom-5 duration-300">
          {/* Header Panel */}
          <div className="p-5 bg-gradient-to-r from-neutral-950 via-neutral-900 to-amber-950 text-white relative">
            <div className="flex items-center gap-3">
              <div className="h-10 w-10 rounded-full bg-amber-500/10 border border-amber-500/30 grid place-items-center text-amber-500">
                <Sparkles className="h-5 w-5 text-amber-400 animate-pulse" />
              </div>
              <div>
                <h4 className="font-display font-bold leading-tight">resume-zen Support</h4>
                <p className="text-[10px] text-amber-400/90 font-medium">Verified Support Center ✦</p>
              </div>
            </div>
            <div className="mt-5 space-y-1">
              <h3 className="text-xl font-bold tracking-tight">
                Hey {user ? user.email?.split("@")[0] : "Chotuu"} 👋
              </h3>
              <p className="text-xs text-muted-foreground/80 text-neutral-400">
                How can we help you today?
              </p>
            </div>

            {/* Support avatars */}
            <div className="absolute top-5 right-5 flex -space-x-2">
              <div className="h-8 w-8 rounded-full border border-neutral-800 bg-neutral-900 grid place-items-center text-[10px] font-bold text-amber-400 font-serif">J</div>
              <div className="h-8 w-8 rounded-full border border-neutral-800 bg-neutral-900 grid place-items-center text-[10px] font-bold text-neutral-400">AI</div>
            </div>
          </div>

          {/* Body Content according to Tab */}
          <div className="flex-1 overflow-y-auto p-4 bg-background">
            {activeTab === "home" && (
              <div className="space-y-4 animate-in fade-in duration-200">
                {/* Search box */}
                <div className="relative">
                  <Input
                    placeholder="Search for help..."
                    value={searchQuery}
                    onChange={(e) => setSearchQuery(e.target.value)}
                    className="pl-9 h-10 rounded-xl bg-card border-border"
                  />
                  <span className="absolute left-3 top-3 text-muted-foreground">🔍</span>
                </div>

                {/* FAQ Block */}
                <div className="space-y-2">
                  <span className="text-[10px] uppercase font-bold tracking-wider text-muted-foreground">Frequently Asked Questions</span>
                  <div className="space-y-2 max-h-[170px] overflow-y-auto pr-1">
                    {filteredFaqs.length > 0 ? (
                      filteredFaqs.map((faq, idx) => (
                        <details key={idx} className="group border border-border rounded-xl bg-card p-2 text-xs leading-normal">
                          <summary className="font-semibold text-foreground/90 cursor-pointer flex items-center justify-between hover:text-foreground">
                            <span>{faq.q}</span>
                            <ChevronRight className="h-3.5 w-3.5 text-muted-foreground transition-transform group-open:rotate-90" />
                          </summary>
                          <p className="mt-2 text-muted-foreground pl-1">{faq.a}</p>
                        </details>
                      ))
                    ) : (
                      <p className="text-xs text-muted-foreground text-center py-2">No matching FAQs found.</p>
                    )}
                  </div>
                </div>

                {/* Direct Contact Card */}
                <div className="p-3.5 rounded-2xl bg-secondary/40 border border-border flex items-start gap-3">
                  <Mail className="h-5 w-5 text-amber-600 dark:text-amber-400 shrink-0 mt-0.5" />
                  <div className="text-xs space-y-1">
                    <p className="font-bold">Contact Developer directly</p>
                    <p className="text-muted-foreground">For manual unlocks, payment failures, or queries, email us at:</p>
                    <a href="mailto:jayeshneo07@gmail.com" className="font-mono text-primary font-semibold select-all">
                      jayeshneo07@gmail.com
                    </a>
                  </div>
                </div>

                {/* Quick Query Chat shortcut */}
                <Button
                  className="w-full rounded-2xl h-11 bg-neutral-900 hover:bg-neutral-800 text-white text-xs font-semibold flex items-center justify-center gap-1.5 cursor-pointer"
                  onClick={() => setActiveTab("messages")}
                >
                  <MessageSquare className="h-4 w-4" /> Start Live AI Support Chat
                </Button>
              </div>
            )}

            {activeTab === "messages" && (
              <div className="h-full flex flex-col animate-in fade-in duration-200">
                {/* Messages area */}
                <div className="flex-1 overflow-y-auto space-y-3 pr-1 max-h-[220px]">
                  {messages.map((m) => (
                    <div key={m.id} className={cn("flex", m.sender === "user" ? "justify-end" : "justify-start")}>
                      <div
                        className={cn(
                          "max-w-[85%] rounded-2xl px-3 py-2.5 text-xs leading-normal",
                          m.sender === "user"
                            ? "bg-neutral-950 text-white rounded-br-none"
                            : "bg-card border border-border rounded-bl-none text-foreground/90"
                        )}
                      >
                        {m.text}
                      </div>
                    </div>
                  ))}
                  {isTyping && (
                    <div className="flex justify-start">
                      <div className="bg-card border border-border rounded-2xl rounded-bl-none px-3 py-2.5 text-xs text-muted-foreground">
                        <span className="typing-dot" /><span className="typing-dot" /><span className="typing-dot" />
                      </div>
                    </div>
                  )}
                  <div ref={chatEndRef} />
                </div>

                {/* Quick Helper Chips */}
                <div className="py-2 flex flex-wrap gap-1.5 border-t border-border mt-3">
                  <button
                    type="button"
                    onClick={() => handleOptionClick("Payment Failure 💳", "fail")}
                    className="text-[10px] font-medium border border-border hover:bg-accent px-2 py-1 rounded-full cursor-pointer"
                  >
                    💳 Payment Failed
                  </button>
                  <button
                    type="button"
                    onClick={() => handleOptionClick("My Resume is Locked 🔒", "lock")}
                    className="text-[10px] font-medium border border-border hover:bg-accent px-2 py-1 rounded-full cursor-pointer"
                  >
                    🔒 Editor Locked
                  </button>
                  <button
                    type="button"
                    onClick={() => handleOptionClick("Email Developer ✉️", "email")}
                    className="text-[10px] font-medium border border-border hover:bg-accent px-2 py-1 rounded-full cursor-pointer"
                  >
                    ✉️ Support Email
                  </button>
                </div>

                {/* Input Form */}
                <form
                  onSubmit={(e) => {
                    e.preventDefault();
                    handleSendMessage();
                  }}
                  className="flex items-center gap-2 border-t border-border pt-2"
                >
                  <Input
                    placeholder="Type a message..."
                    value={inputText}
                    onChange={(e) => setInputText(e.target.value)}
                    className="flex-1 rounded-xl h-9 text-xs bg-card border-border pr-2"
                  />
                  <Button type="submit" size="icon" className="h-9 w-9 rounded-xl bg-neutral-950 text-white shrink-0 cursor-pointer">
                    <Send className="h-3.5 w-3.5" />
                  </Button>
                </form>
              </div>
            )}

            {activeTab === "help" && (
              <div className="space-y-4 animate-in fade-in duration-200">
                <span className="text-[10px] uppercase font-bold tracking-wider text-muted-foreground">Knowledge Base</span>
                
                <div className="space-y-3">
                  <div className="p-3 border border-border rounded-2xl bg-card space-y-1">
                    <h5 className="font-semibold text-xs text-foreground/90">Bilingual & Multilingual Exports</h5>
                    <p className="text-xs text-muted-foreground leading-relaxed">
                      With Premium, you can choose Native or Bilingual layouts from the download dropdown. Bilingual renders side-by-side or stacked formats, presenting English alongside target translations cleanly for global hiring.
                    </p>
                  </div>
                  
                  <div className="p-3 border border-border rounded-2xl bg-card space-y-1">
                    <h5 className="font-semibold text-xs text-foreground/90">The UPI Settlement Rules</h5>
                    <p className="text-xs text-muted-foreground leading-relaxed">
                      All UPI transfers settle instantly. Ensure you copy the 12-digit numeric reference code carefully to unlock. Fake UTR reference inputs are automatically flagged by our ledger auditer.
                    </p>
                  </div>

                  <div className="p-3 border border-border rounded-2xl bg-card flex items-start gap-2.5 bg-amber-500/5 border-amber-500/20 text-amber-900 dark:text-amber-400">
                    <AlertCircle className="h-4 w-4 shrink-0 mt-0.5" />
                    <div className="text-[11px] leading-normal">
                      <p className="font-bold">Need Immediate Help?</p>
                      <p className="opacity-90">Send your transaction screenshot and resume ID to <span className="font-semibold font-mono">jayeshneo07@gmail.com</span> for a manual override.</p>
                    </div>
                  </div>
                </div>
              </div>
            )}
          </div>

          {/* Navigation Bar at Bottom */}
          <div className="border-t border-border/80 bg-card p-1 flex items-center justify-around text-xs shrink-0">
            <button
              onClick={() => setActiveTab("home")}
              className={cn(
                "flex-1 py-2 flex flex-col items-center gap-0.5 text-muted-foreground hover:text-foreground cursor-pointer transition-colors",
                activeTab === "home" ? "text-neutral-950 font-bold" : ""
              )}
            >
              <Home className="h-4 w-4" />
              <span className="text-[9px]">Home</span>
            </button>
            <button
              onClick={() => setActiveTab("messages")}
              className={cn(
                "flex-1 py-2 flex flex-col items-center gap-0.5 text-muted-foreground hover:text-foreground cursor-pointer transition-colors",
                activeTab === "messages" ? "text-neutral-950 font-bold" : ""
              )}
            >
              <MessageSquare className="h-4 w-4" />
              <span className="text-[9px]">Messages</span>
            </button>
            <button
              onClick={() => setActiveTab("help")}
              className={cn(
                "flex-1 py-2 flex flex-col items-center gap-0.5 text-muted-foreground hover:text-foreground cursor-pointer transition-colors",
                activeTab === "help" ? "text-neutral-950 font-bold" : ""
              )}
            >
              <HelpCircle className="h-4 w-4" />
              <span className="text-[9px]">Help</span>
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
